### ISSUE TITLE
Maven Coordinates

### ISSUE THREAD

**Issue by chris-smith-zocdoc** [dmlc/tl2cgen#12]
Is treelite4j available on maven central? 

I'm interesting in using the java bindings but didn't see it published. 

https://search.maven.org/search?q=treelite

**Comment by hcho3** [comment]
Hi everyone, apologies for the late update. I've had not had any time to maintain Treelite4J (now TL2cgen4J), and it's still not available on Maven Central.

I am looking for someone who wants to take over the Java package (or TL2cgen in general). If you are interested, reach out to me at chohyu01@cs.washington.edu.
